const EVENTOS_CODE_API='https://pyodzkmreynyxhvxstta.supabase.co/functions/v1/eventos-code-api';
const DEVICE_KEY='eventos-device-token-v1';
const WORKSPACE_KEY='eventos-workspace-v1';
const META_KEY='eventos-code-meta-v1';
const DELETE_KEY='eventos-code-deletes-v1';

function codeSafeParse(key,fallback){try{return JSON.parse(localStorage.getItem(key)||'')||fallback}catch{return fallback}}
function codeUid(){if(crypto?.randomUUID)return crypto.randomUUID();return'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==='x'?r:(r&3|8);return v.toString(16)})}
function codeDeviceToken(){let t=localStorage.getItem(DEVICE_KEY);if(!t){const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);t=Array.from(bytes).map(b=>b.toString(16).padStart(2,'0')).join('');localStorage.setItem(DEVICE_KEY,t)}return t}
function codeNow(){return new Date().toISOString()}
function codeToday(){return new Date().toISOString().slice(0,10)}
function codeDate(v){if(!v)return dateLabel();const d=new Date(`${v}T12:00:00`);return Number.isNaN(d.getTime())?dateLabel():new Intl.DateTimeFormat('es-ES',{day:'2-digit',month:'short',year:'numeric'}).format(d)}
function codeIsoFromLabel(label){const s=String(label||'').toLowerCase().replace(/\./g,'').trim();const m=s.match(/^(\d{1,2})\s+([a-záéíóú]+)\s+(\d{4})$/i);if(!m)return codeToday();const months={ene:1,enero:1,feb:2,febrero:2,mar:3,marzo:3,abr:4,abril:4,may:5,mayo:5,jun:6,junio:6,jul:7,julio:7,ago:8,agosto:8,sep:9,sept:9,septiembre:9,oct:10,octubre:10,nov:11,noviembre:11,dic:12,diciembre:12};const mo=months[m[2]];return mo?`${m[3]}-${String(mo).padStart(2,'0')}-${String(Number(m[1])).padStart(2,'0')}`:codeToday()}
function codeRecordDate(item){return /^\d{4}-\d{2}-\d{2}$/.test(String(item?.isoDate||''))?item.isoDate:codeIsoFromLabel(item?.date)}
function codeSignature(item,key){if(key==='savings')return JSON.stringify([item.name,Number(item.amount||0),codeRecordDate(item)]);if(key==='expenses')return JSON.stringify([item.name,item.category,Number(item.eventSlot||0),Number(item.amount||0),codeRecordDate(item)]);return JSON.stringify([Number(item.slot||0),item.name,Number(item.amount||0),codeRecordDate(item)])}

let codeWorkspace=codeSafeParse(WORKSPACE_KEY,null);
let codeMeta=codeSafeParse(META_KEY,{goalUpdatedAt:null,lastSyncAt:null});
let codeDeletes=codeSafeParse(DELETE_KEY,[]);
let codeDirty=false;
let codeSyncing=false;
let codeLoading=false;
let codeTimer=null;
let codePoll=null;
let codeLastSnapshot=null;

const codeBaseSaveState=saveState;
const codeBaseRender=render;
const codeBaseOpenSettings=openSettings;

function persistCode(){try{codeWorkspace?localStorage.setItem(WORKSPACE_KEY,JSON.stringify(codeWorkspace)):localStorage.removeItem(WORKSPACE_KEY);localStorage.setItem(META_KEY,JSON.stringify(codeMeta));localStorage.setItem(DELETE_KEY,JSON.stringify(codeDeletes))}catch{}}
function codeSnapshot(){const s={goal:Number(state.goal||0)};['savings','expenses','events'].forEach(k=>s[k]=new Map((state[k]||[]).map(x=>[x.id,codeSignature(x,k)])));return s}
function codeNormalize(mark=false){const stamp=codeNow();['savings','expenses','events'].forEach(k=>{state[k]=Array.isArray(state[k])?state[k]:[];state[k]=state[k].map(item=>{const n={...item};n.id=n.id||codeUid();n.isoDate=codeRecordDate(n);const before=codeLastSnapshot?.[k]?.get(n.id),after=codeSignature(n,k);if(!n.updatedAt||(mark&&before!==after))n.updatedAt=stamp;return n})});if(!codeMeta.goalUpdatedAt)codeMeta.goalUpdatedAt=stamp}
function codeQueueDeletes(previous){if(!codeWorkspace||!previous)return;const table={savings:'eventos_savings',expenses:'eventos_expenses',events:'eventos_events'};['savings','expenses','events'].forEach(k=>{const current=new Set((state[k]||[]).map(x=>x.id));for(const id of previous[k]?.keys?.()||[]){if(!current.has(id)&&!codeDeletes.some(x=>x.workspaceId===codeWorkspace.id&&x.table===table[k]&&x.id===id))codeDeletes.push({workspaceId:codeWorkspace.id,table:table[k],id,deletedAt:codeNow()})}})}

saveState=function(){const prev=codeLastSnapshot;codeNormalize(true);if(prev&&Number(prev.goal)!==Number(state.goal))codeMeta.goalUpdatedAt=codeNow();codeQueueDeletes(prev);try{codeBaseSaveState()}catch(error){console.error(error);toast('No se pudo guardar en el dispositivo')}codeDirty=true;codeLastSnapshot=codeSnapshot();persistCode();scheduleCodeSync()};
render=function(){codeBaseRender();decorateCodeStatus()};

async function codeApi(action,extra={}){const res=await fetch(EVENTOS_CODE_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,deviceToken:codeDeviceToken(),...extra}),cache:'no-store'});let data={};try{data=await res.json()}catch{}if(!res.ok)throw new Error(data?.error||`Error ${res.status}`);return data}
function codeStatePayload(){codeNormalize(false);return{goal:Number(state.goal)||7000,goalUpdatedAt:codeMeta.goalUpdatedAt||codeNow(),savings:(state.savings||[]).map(x=>({id:x.id,name:x.name,amount:Number(x.amount)||0,isoDate:codeRecordDate(x),updatedAt:x.updatedAt||codeNow()})),expenses:(state.expenses||[]).map(x=>({id:x.id,name:x.name,category:x.category,eventSlot:Number(x.eventSlot)||0,amount:Number(x.amount)||0,isoDate:codeRecordDate(x),updatedAt:x.updatedAt||codeNow()})),events:(state.events||[]).map(x=>({id:x.id,slot:Number(x.slot)||1,name:x.name,amount:Number(x.amount)||0,isoDate:codeRecordDate(x),updatedAt:x.updatedAt||codeNow()}))}}
function applyCodeRemote(data){if(data?.workspace){codeWorkspace={id:data.workspace.id,name:data.workspace.name,inviteCode:data.workspace.inviteCode,role:data.workspace.role}}const r=data?.state;if(!r)return;state={goal:Number(r.goal||7000),savings:(r.savings||[]).map(x=>({id:x.id,name:x.name,amount:Number(x.amount),date:codeDate(x.isoDate),isoDate:x.isoDate,updatedAt:x.updatedAt})),expenses:(r.expenses||[]).map(x=>({id:x.id,name:x.name,category:x.category,eventSlot:Number(x.eventSlot)||0,amount:Number(x.amount),date:codeDate(x.isoDate),isoDate:x.isoDate,updatedAt:x.updatedAt})),events:(r.events||[]).map(x=>({id:x.id,slot:Number(x.slot)||1,name:x.name,amount:Number(x.amount),date:codeDate(x.isoDate),isoDate:x.isoDate,updatedAt:x.updatedAt}))};codeMeta.goalUpdatedAt=r.goalUpdatedAt||codeMeta.goalUpdatedAt;codeMeta.lastSyncAt=codeNow();codeDirty=false;codeDeletes=codeDeletes.filter(x=>x.workspaceId!==codeWorkspace?.id);try{codeBaseSaveState()}catch{}codeLastSnapshot=codeSnapshot();persistCode()}

async function createCodeWorkspace(){if(codeSyncing)return;const localCopy=JSON.parse(JSON.stringify(state));codeNormalize(false);setCodeGateMessage('Creando espacio compartido…');try{const data=await codeApi('create',{state:codeStatePayload()});codeWorkspace={id:data.workspace.id,name:data.workspace.name,inviteCode:data.workspace.inviteCode,role:'owner'};state=localCopy;codeNormalize(true);codeDirty=true;codeLastSnapshot=codeSnapshot();persistCode();await syncCodeState(true);hideCodeGate();render();toast('Espacio compartido creado')}catch(error){setCodeGateMessage(error.message||'No se pudo crear el espacio')}}
async function joinCodeWorkspace(){const input=document.getElementById('codeInviteInput');const code=String(input?.value||'').trim().toUpperCase();if(!/^[A-F0-9]{12}$/.test(code)){setCodeGateMessage('El código debe tener 12 caracteres.');return}setCodeGateMessage('Entrando…');try{const data=await codeApi('join',{code});applyCodeRemote(data);hideCodeGate();render();toast('Ya compartís el mismo espacio')}catch(error){setCodeGateMessage(error.message||'No se pudo usar ese código')}}
async function loadCodeState(force=false){if(!codeWorkspace||codeLoading||(!force&&codeDirty)||!navigator.onLine)return;codeLoading=true;try{const data=await codeApi('load',{workspaceId:codeWorkspace.id});applyCodeRemote(data);render()}catch(error){console.error('loadCodeState',error);if(String(error.message).includes('no autorizado')){codeWorkspace=null;persistCode();showCodeGate('choose')} }finally{codeLoading=false;decorateCodeStatus()}}
async function syncCodeState(force=false){if(!codeWorkspace||codeSyncing||codeLoading||(!force&&!codeDirty&&!codeDeletes.length))return;if(!navigator.onLine){codeDirty=true;decorateCodeStatus();return}codeSyncing=true;try{const deletions=codeDeletes.filter(x=>x.workspaceId===codeWorkspace.id);const data=await codeApi('sync',{workspaceId:codeWorkspace.id,state:codeStatePayload(),deletes:deletions});applyCodeRemote(data);render();if(force)toast('Sincronizado')}catch(error){console.error('syncCodeState',error);codeDirty=true;toast('Guardado en el dispositivo; se sincronizará después')}finally{codeSyncing=false;decorateCodeStatus()}}
function scheduleCodeSync(){if(!codeWorkspace)return;clearTimeout(codeTimer);codeTimer=setTimeout(()=>syncCodeState(false),500)}

function decorateCodeStatus(){const header=document.querySelector('.premium-header .header-side');if(!header)return;let dot=header.querySelector('.cloud-dot');if(!dot){dot=document.createElement('span');dot.className='cloud-dot';header.appendChild(dot)}const online=Boolean(navigator.onLine&&codeWorkspace&&!codeDirty);dot.classList.toggle('online',online);dot.title=!navigator.onLine?'Sin conexión · guardando en este dispositivo':online?'Sincronización al día':codeWorkspace?'Cambios pendientes':'Sin espacio compartido'}

function mountCodeGate(){if(document.getElementById('cloudAuthGate'))return;const gate=document.createElement('div');gate.id='cloudAuthGate';gate.className='cloud-gate';gate.hidden=true;gate.innerHTML='<div class="cloud-gate-card"><div class="cloud-gate-logo">EV</div><h2 id="codeGateTitle">Eventos compartidos</h2><p id="codeGateText">Sin correo y sin contraseña.</p><div id="codeGateActions" class="cloud-workspace-actions"></div><div id="codeGateMessage" class="cloud-gate-message"></div></div>';document.body.appendChild(gate)}
function setCodeGateMessage(t){const n=document.getElementById('codeGateMessage');if(n)n.textContent=t||''}
function hideCodeGate(){const g=document.getElementById('cloudAuthGate');if(g)g.hidden=true}
function showCodeGate(mode='choose'){mountCodeGate();const g=document.getElementById('cloudAuthGate');g.hidden=false;const title=document.getElementById('codeGateTitle'),txt=document.getElementById('codeGateText'),actions=document.getElementById('codeGateActions');setCodeGateMessage('');if(mode==='join'){title.textContent='Unirme al espacio';txt.textContent='Introduce el código de 12 caracteres que te comparta tu amigo.';actions.innerHTML='<input id="codeInviteInput" maxlength="12" autocapitalize="characters" autocomplete="off" placeholder="CÓDIGO DE INVITACIÓN"><button type="button" id="joinCodeBtn" class="cloud-main-btn">Unirme con código</button><button type="button" id="cancelCodeGate" class="cloud-link-btn">Cancelar</button>'}else{title.textContent='Eventos compartidos';txt.textContent='Sin correo. Sin contraseña. Cada móvil tiene una identidad técnica privada.';actions.innerHTML='<button type="button" id="createCodeBtn" class="cloud-main-btn">Crear mi espacio</button><div class="cloud-separator">o</div><input id="codeInviteInput" maxlength="12" autocapitalize="characters" autocomplete="off" placeholder="CÓDIGO DE INVITACIÓN"><button type="button" id="joinCodeBtn" class="cloud-secondary-btn">Unirme con código</button><button type="button" id="localOnlyBtn" class="cloud-link-btn">Usar solo en este dispositivo</button>'}document.getElementById('createCodeBtn')?.addEventListener('click',createCodeWorkspace);document.getElementById('joinCodeBtn')?.addEventListener('click',joinCodeWorkspace);document.getElementById('cancelCodeGate')?.addEventListener('click',hideCodeGate);document.getElementById('localOnlyBtn')?.addEventListener('click',hideCodeGate)}

openSettings=function(){codeBaseOpenSettings();const card=document.createElement('section');card.className='cloud-settings-card';const connected=Boolean(codeWorkspace);const invite=codeWorkspace?.inviteCode||'—';const syncText=connected?(codeDirty?'Cambios pendientes de sincronizar':`Sincronizado${codeMeta.lastSyncAt?' · '+new Intl.DateTimeFormat('es-ES',{hour:'2-digit',minute:'2-digit'}).format(new Date(codeMeta.lastSyncAt)):''}`):'Solo en este dispositivo';card.innerHTML=`<div class="cloud-settings-title">Datos y sincronización</div><p>${clean(syncText)}</p>${connected?`<div class="invite-code-row"><code>${clean(invite)}</code><button type="button" id="copyCodeInvite">Copiar</button></div><button type="button" class="cloud-secondary-btn" id="syncCodeNow">Sincronizar ahora</button><button type="button" class="cloud-secondary-btn" id="joinOtherCode">Unirme con otro código</button>`:`<p>No hace falta correo ni contraseña.</p><button type="button" class="cloud-secondary-btn" id="activateCodeShare">Activar espacio compartido</button>`}<button type="button" class="cloud-secondary-btn" id="exportCodeBackup">Exportar copia de seguridad</button>`;sheetForm.appendChild(card);document.getElementById('copyCodeInvite')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(invite);toast('Código copiado')}catch{toast(invite)}});document.getElementById('syncCodeNow')?.addEventListener('click',()=>syncCodeState(true));document.getElementById('joinOtherCode')?.addEventListener('click',()=>{closeSheet();showCodeGate('join')});document.getElementById('activateCodeShare')?.addEventListener('click',()=>{closeSheet();showCodeGate('choose')});document.getElementById('exportCodeBackup')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify({version:5,exportedAt:codeNow(),workspace:codeWorkspace,state},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`eventos-backup-${codeToday()}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Copia de seguridad creada')})};

async function bootCodeCloud(){mountCodeGate();codeNormalize(false);try{codeBaseSaveState()}catch{}codeLastSnapshot=codeSnapshot();if(codeWorkspace){await loadCodeState(true)}else{showCodeGate('choose')}clearInterval(codePoll);codePoll=setInterval(()=>{if(document.hidden||!navigator.onLine||!codeWorkspace)return;if(codeDirty||codeDeletes.length)syncCodeState(false);else loadCodeState(false)},15000);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&navigator.onLine&&codeWorkspace){if(codeDirty||codeDeletes.length)syncCodeState(false);else loadCodeState(true)}});window.addEventListener('online',()=>{toast('Conexión recuperada');if(codeWorkspace)syncCodeState(false);render()});window.addEventListener('offline',()=>{toast('Sin conexión · los cambios se guardarán aquí');render()});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.error));render()}

bootCodeCloud();
