const euro=n=>Number(n||0).toLocaleString('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2})+' €';
const load=(k)=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let savings=load('eventos_v7_savings'),expenses=load('eventos_v7_expenses'),events=load('eventos_v7_events'),filter='Todos',modalMode='';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function go(page){$$('.page').forEach(x=>x.classList.toggle('active',x.id===page));$$('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page));window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-page]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.page)));
function renderSavings(){const total=savings.reduce((a,b)=>a+Number(b.amount),0),pct=Math.min(100,total/7000*100);$('#saveTotal').textContent=euro(total);$('#savePct').textContent=Math.round(pct)+'%';$('#saveBar').style.width=pct+'%';$('#saveRing').style.setProperty('--p',pct+'%');$('#savingList').innerHTML=savings.length?savings.slice().reverse().map((x,i)=>`<div class="item"><div class="avatar">€</div><div><b>${x.note||'Aportación'}</b><div class="meta">${x.date}</div></div><div class="money plus">+${euro(x.amount)}</div></div>`).join(''):`<div class="empty"><div><div class="emptyicon">€</div>Todavía no hay aportaciones.<br>Añade la primera cuando quieras.</div></div>`}
function renderExpenses(){const total=expenses.reduce((a,b)=>a+Number(b.amount),0);$('#investTotal').textContent=euro(total);const rows=expenses.filter(x=>filter==='Todos'||x.category===filter);$('#expenseList').innerHTML=rows.length?rows.slice().reverse().map(x=>`<div class="item"><div class="avatar">€</div><div><b>${x.name}</b><div class="meta">${x.category} · ${x.date}</div></div><div class="money minus">-${euro(x.amount)}</div></div>`).join(''):`<div class="empty"><div><div class="emptyicon">▤</div>No hay gastos en esta vista.<br>Añade un gasto para llevar el control.</div></div>`}
function renderEvents(){const total=events.reduce((a,b)=>a+Number(b.amount),0),avg=events.length?total/events.length:0,max=events.length?Math.max(...events.map(x=>Number(x.amount))):0;$('#benefitTotal').textContent=euro(total);$('#eventCount').textContent=events.length;$('#eventAvg').textContent=euro(avg);$('#eventMax').textContent=euro(max);$('#eventList').innerHTML=events.length?events.slice().reverse().map(x=>`<div class="item"><div class="avatar">🏆</div><div><b>${x.name}</b><div class="meta">${x.date}</div></div><div class="money plus">+${euro(x.amount)}</div></div>`).join(''):`<div class="empty"><div><div class="emptyicon">▣</div>Todavía no hay eventos.<br>Añade el primero para empezar a sumar ganancias.</div></div>`}
function openModal(mode){modalMode=mode;const box=$('#modalFields');if(mode==='saving'){ $('#modalTitle').textContent='Añadir dinero';$('#modalSub').textContent='Registra una nueva aportación a la hucha.';box.innerHTML='<div class="field"><label>Importe</label><input id="fAmount" type="number" inputmode="decimal" min="0" step="0.01" placeholder="0,00 €"></div><div class="field"><label>Concepto</label><input id="fName" placeholder="Aportación"></div>'}if(mode==='expense'){ $('#modalTitle').textContent='Añadir gasto';$('#modalSub').textContent='Añade una inversión del evento.';box.innerHTML='<div class="field"><label>Concepto</label><input id="fName" placeholder="Ej. 5 palmeras"></div><div class="field"><label>Importe</label><input id="fAmount" type="number" inputmode="decimal" min="0" step="0.01" placeholder="0,00 €"></div><div class="field"><label>Categoría</label><select id="fCategory"><option>Material</option><option>Catering</option><option>Local</option><option>Otros</option></select></div>'}if(mode==='event'){ $('#modalTitle').textContent='Añadir evento';$('#modalSub').textContent='Registra la ganancia de este evento.';box.innerHTML='<div class="field"><label>Nombre del evento</label><input id="fName" placeholder="Primer evento"></div><div class="field"><label>Ganancia</label><input id="fAmount" type="number" inputmode="decimal" min="0" step="0.01" placeholder="0,00 €"></div>'}$('#modalBack').classList.add('show');setTimeout(()=>$('#fAmount')?.focus(),100)}
function closeModal(){$('#modalBack').classList.remove('show')}
$('#addMoney').onclick=()=>openModal('saving');$('#addExpense').onclick=()=>openModal('expense');$('#addEvent').onclick=()=>openModal('event');$('#cancelModal').onclick=closeModal;$('#modalBack').addEventListener('click',e=>{if(e.target===$('#modalBack'))closeModal()});
$('#saveModal').onclick=()=>{const amount=Number($('#fAmount')?.value||0);if(!(amount>0))return;const date=new Date().toLocaleDateString('es-ES',{day:'2-digit',month:'short',year:'numeric'});if(modalMode==='saving'){savings.push({amount,note:$('#fName')?.value.trim()||'Aportación',date});save('eventos_v7_savings',savings);renderSavings()}if(modalMode==='expense'){expenses.push({amount,name:$('#fName')?.value.trim()||'Gasto',category:$('#fCategory')?.value||'Otros',date});save('eventos_v7_expenses',expenses);renderExpenses()}if(modalMode==='event'){events.push({amount,name:$('#fName')?.value.trim()||`Evento ${events.length+1}`,date});save('eventos_v7_events',events);renderEvents()}closeModal()};
$$('.chip').forEach(c=>c.onclick=()=>{filter=c.dataset.filter;$$('.chip').forEach(x=>x.classList.toggle('active',x===c));renderExpenses()});
$('#clearSavings').onclick=()=>{if(confirm('¿Vaciar todas las aportaciones?')){savings=[];save('eventos_v7_savings',savings);renderSavings()}};$('#clearExpenses').onclick=()=>{if(confirm('¿Vaciar todos los gastos?')){expenses=[];save('eventos_v7_expenses',expenses);renderExpenses()}};$('#clearEvents').onclick=()=>{if(confirm('¿Vaciar todos los eventos?')){events=[];save('eventos_v7_events',events);renderEvents()}};
renderSavings();renderExpenses();renderEvents();